### ISSUE TITLE
Queued emails are randomly lost

### ISSUE THREAD

**Issue by manandre** [Birmania/smtp-mailing-queue#1]
I have started to use the "smtp-mailing-queue" plugin to send to subscribers published articles notification, within the limits of my provider. But I discovered that the number of emails sent did not match the number of subscribers. After analysis of the plugin [code](https://github.com/Birmania/smtp-mailing-queue/blob/22a1bf4bae5ec2b5620a7aa646d0312ced22114d/classes/SMTPMailingQueue.php#L265), I discovered that the PHP `microtime(true)` function is used to ensure uniqueness of stored email filename (in json format).
But, unfortunately, the obtained precision is often not the microsecond as [it depends on the float precision configured in php.ini](https://www.oreilly.com/library/view/php-in-a/0596100671/re64.html).
So a stored email can be overridden by a next one, as it gets the same microtime() result...
Currently, as I cannot change the php configuration (shared server), I have workarounded that by adding "manually" a call to the `usleep(20000)` function after each call to microtime() to ensure uniqueness, as `microtime(true)` reports something like `1595870079.9167` on my server.
I think we should find a safer uniqueness provider!

**Comment by Birmania** [comment]
Hi @manandre,

You are right about this uniqueness provider !

What do you think if we update to [uniqid](https://www.php.net/manual/fr/function.uniqid.php) function (with more_entropy parameter set to TRUE) ?
It also rely on date (which is bad in our case) but more_entropy allow to add combined LCG number at the end.
Thanks for your report !

Yours faithfully,
Birmania

**Comment by manandre** [comment]
Yes, good idea!
It also has the advantage to keep generating values in the lexicographical order, what permits to send emails in the received order 👍
